name: slack-release-notification
description: Announce release on Slack

inputs:
  slack_webhook_url:
    required: true

runs:
  using: "composite"
  steps:
    - name: Slackify the release body
      id: release_body
      uses: LoveToKnow/slackify-markdown-action@v1.0.0
      with:
        text: ${{ github.event.release.body }}
    - name: Slack Notification on SUCCESS
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
      with:
        text: ${{ github.repository }} as been deployed to production
        blocks: |
          [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "${{ github.repository }} ${{ github.event.release.tag_name }} has been deployed to production"
              }
            },
            {
              "type": "context",
              "elements": [
                {
                  "type": "image",
                  "image_url": "${{ github.event.sender.avatar_url }}",
                  "alt_text": "${{ github.actor }}"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Author:* ${{ github.actor }}"
                }
              ]
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Information:*"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": ${{ toJSON(steps.release_body.outputs.text) }}
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "${{ github.event.release.html_url }}"
              }
            }
          ]
